library(iCNV)

##### IMPORTANT #####
# This demo mainly demonstrate function in the iCNV packages.
# For detailed notation and pipeline function, please visit https://github.com/zhouzilu/iCNV/blob/master/vignettes/iCNV-vignette.Rmd

####################################################
####################################################
##########                                ##########
##########           data input           ##########
##########                                ##########
####################################################
####################################################

# We need our input data. There are 9 list, each list have 10 samples
# sequencing plr and position: ngs_plr, ngs_plr.pos
# sequencing baf and position: ngs_baf, ngs_baf.pos
# snp array lrr and position: snp_lrr, snp_lrr.pos
# snp array snp and position: snp_baf, snp_baf.pos
# sample id: sampname_qc

# setwd to demo
setwd('demo')
# array data from standard format
dir='array'
projectname = "icnv.demo"
pattern=paste0('*.csv.arrayicnv$')
get_array_intput(dir,pattern,chr=22,projectname)
load(file.path(dir,paste0(projectname,'array_lrrbaf_22.rda')))

# ngs plr data from rda file generated by CODEX
load('ngs/icnv.demoplrObj_22_2.rda')

# ngs baf data from vcf file
dir='ngs/baf'
bambaf_from_vcf(dir,'vcf.sample.list',chr=22)
load(file.path(dir,paste0(projectname,'bambaf_22.rda')))

str(ngs_plr) # List of n vector, each one is the PLR for an exon
str(ngs_plr.pos) # List of n matrix (p x 2), each one is the start and end location for an exon
str(ngs_baf) # List of n vector, each one is the variants BAF from .bam
str(ngs_baf.pos) # List of n vector, each one is the variants BAF position
str(snp_lrr) # List of n vector, each one is the normalized LRR for a SNP
str(snp_lrr.pos) # List of n vector, each one is a SNP position
str(snp_baf) # List of n vector, each one is the BAF for a SNP
str(snp_baf.pos) # List of n vector, each one is the SNP BAF position
str(sampname_qc) # Vector of sample id or name

####################################################
####################################################
##########                                ##########
##########    iCNV without genotype       ##########
##########                                ##########
####################################################
####################################################

projname='icnv.demo'
icnv_res0=iCNV_detection(ngs_plr,snp_lrr,
                         ngs_baf,snp_baf,
                         ngs_plr.pos,snp_lrr.pos,
                         ngs_baf.pos,snp_baf.pos,
                         projname=projname,CN=0,mu=c(-3,0,2),cap=T,visual = 1)

####################################################
####################################################
##########                                ##########
##########       single sample plot       ##########
##########                                ##########
####################################################
####################################################

plotindi(ngs_plr,snp_lrr,
         ngs_baf,snp_baf,
         ngs_plr.pos,snp_lrr.pos,
         ngs_baf.pos,snp_baf.pos,
         icnv_res0,1)

####################################################
####################################################
##########                                ##########
##########  Zoom in region of interests   ##########
##########                                ##########
####################################################
####################################################

plotHMMscore(icnv_res0,20000000,25000000)

####################################################
####################################################
##########                                ##########
##########        iCNV with genotype      ##########
##########                                ##########
####################################################
####################################################

projname='icnv.demo.geno'
icnv_res1=iCNV_detection(ngs_plr,snp_lrr,
                         ngs_baf,snp_baf,
                         ngs_plr.pos,snp_lrr.pos,
                         ngs_baf.pos,snp_baf.pos,
                         projname=projname,CN=1,mu=c(-3,0,2),cap=T,visual = 1)

####################################################
####################################################
##########                                ##########
##########     Generate readable output   ##########
##########                                ##########
####################################################
####################################################

icnv.output = output_list(icnv_res=icnv_res1,sampleid=sampname_qc, CN=0, min_size=10000)

####################################################
####################################################
#######                                     ########
####### Save output as Genome Browser input ########
#######                                     ########
####################################################
####################################################

gb_input = icnv_output_to_gb(chr=22,icnv.output)

####################################################
####################################################
##########                                ##########
########## iCNV with genotype (all plot)  ##########
##########                                ##########
####################################################
####################################################

projname='icnv.demo.geno.allplot'
icnv_res2=iCNV_detection(ngs_plr,snp_lrr,
                         ngs_baf,snp_baf,
                         ngs_plr.pos,snp_lrr.pos,
                         ngs_baf.pos,snp_baf.pos,
                         projname=projname,CN=1,mu=c(-3,0,2),cap=T,visual = 2)


####################################################
####################################################
##########                                ##########
##########     generate output tables     ##########
##########                                ##########
####################################################
####################################################

icnv.output = output_list(icnv_res2,sampname_qc,CN=1)
head(icnv.output)

# Wanna exclude short CNVs to increase robustness.
icnv.output1 = output_list(icnv_res2,sampname_qc,CN=1,min_size=1000)
head(icnv.output1)


####################################################
####################################################
##########                                ##########
##########       iCNV with NGS only       ##########
##########                                ##########
####################################################
####################################################

projname='icnv.demo.ngs'
icnv_res0=iCNV_detection(ngs_plr=ngs_plr,
                         ngs_baf=ngs_baf,
                         ngs_plr.pos=ngs_plr.pos,
                         ngs_baf.pos=ngs_baf.pos,
                         projname=projname,CN=0,mu=c(-3,0,2),cap=T,visual = 0)

projname='icnv.demo.geno.ngs'
icnv_res1=iCNV_detection(ngs_plr=ngs_plr,
                         ngs_baf=ngs_baf,
                         ngs_plr.pos=ngs_plr.pos,
                         ngs_baf.pos=ngs_baf.pos,
                         projname=projname,CN=1,mu=c(-3,0,2),cap=T,visual = 1)

projname='icnv.demo.geno.allplot.ngs'
icnv_res2=iCNV_detection(ngs_plr=ngs_plr,
                         ngs_baf=ngs_baf,
                         ngs_plr.pos=ngs_plr.pos,
                         ngs_baf.pos=ngs_baf.pos,
                         projname=projname,CN=1,mu=c(-3,0,2),cap=T,visual = 2)

icnv.output = output_list(icnv_res2,sampname_qc,CN=1)
head(icnv.output)

# Wanna exclude short CNVs to increase robustness.
icnv.output1 = output_list(icnv_res2,sampname_qc,CN=1,min_size=1000)
head(icnv.output1)

# Note for WGS
# You could easily generate BED file of all location using bed_generator function in iCNV/utils/bed_generator.R
bed_generator(chr=22,hg=19)
bed_generator(chr=22,hg=19,start=5001,end=10000,by=500)

####################################################
####################################################
##########                                ##########
##########       iCNV with SNP only       ##########
##########                                ##########
####################################################
####################################################

projname='icnv.demo.snp'
icnv_res0=iCNV_detection(snp_lrr=snp_lrr,
                         snp_baf=snp_baf,
                         snp_lrr.pos=snp_lrr.pos,
                         snp_baf.pos=snp_baf.pos,
                         projname=projname,CN=0,mu=c(-3,0,2),cap=T,visual = 0)


projname='icnv.demo.geno.snp'
icnv_res1=iCNV_detection(snp_lrr=snp_lrr,
                         snp_baf=snp_baf,
                         snp_lrr.pos=snp_lrr.pos,
                         snp_baf.pos=snp_baf.pos,
                         projname=projname,CN=1,mu=c(-3,0,2),cap=T,visual = 1)

projname='icnv.demo.geno.allplot.snp'
icnv_res2=iCNV_detection(snp_lrr=snp_lrr,
                         snp_baf=snp_baf,
                         snp_lrr.pos=snp_lrr.pos,
                         snp_baf.pos=snp_baf.pos,
                         projname=projname,CN=1,mu=c(-3,0,2),cap=T,visual = 2)

icnv.output = output_list(icnv_res2,sampname_qc,CN=1)
head(icnv.output)

