#' plot out the NGS plr or array lrr.
#' 
#' For quality checking purpose during intermediate steps
#' 
#' @param intensity Specify the ngs_plr object generated by CODEX or SNP array.
#' @param chr Specify the chromosome you want to generate. Must be of int from 1-22
#' @return void
#' @examples
#' plot_intensity(ngs_plr,chr)
#' plot_intensity(snp_lrr,chr)
#' @export
plot_intensity = function(intensity,chr){
  intensity = do.call(cbind,intensity)
  l=4
  toplot=(intensity-rowMeans(intensity,na.rm=T))/apply(intensity,1,function(x){sd(x,na.rm=T)})
  fields::image.plot(x=seq(1,nrow(toplot)),y=seq(1,ncol(toplot)),z=pmin(pmax(toplot,-l),l),zlim=c(-l,l),xlab=paste0('chr',chr),ylab='samples')
}
