#' plot out the NGS plr.
#' @param chr Specify the chromosome you want to generate. Must be of int from 1-22
#' @param ngs_plr Specify the ngs_plr object generated by CODEX.
#' @return void
#' @examples
#' library(fields)
#' plot_ngs_plr(ngs_plr,chr)
#' @export
plot_ngs_plr = function(ngs_plr,chr){
  plr = do.call(cbind,ngs_plr)
  l=4
  toplot=(plr-rowMeans(plr,na.rm=T))/apply(plr,1,function(x){sd(x,na.rm=T)})
  fields::image.plot(x=seq(1,nrow(toplot)),y=seq(1,ncol(toplot)),z=pmin(pmax(toplot,-l),l),zlim=c(-l,l),xlab=paste0('chr',chr),ylab='samples')
}
